### ISSUE TITLE
Bug: Using lat lon based polygon release fails

### ISSUE THREAD

**Issue by 465b** [oceantracker/oceantracker#8]
```python
C000 >>> Error:  Unexpected error in case number [ 0] 
C000       hint: check above or .err file
C000 'PolygonRelease' object has no attribute 'IDstr'
C000 Traceback (most recent call last):
  File "/home/zmaw/u301513/Documents/scr/postdoc/eDNA/oceantracker/oceantracker/_oceantracker_case_runner.py", line 110, in run_case
    self._initial_setup_all_classes(si.working_params)
  File "/home/zmaw/u301513/Documents/scr/postdoc/eDNA/oceantracker/oceantracker/_oceantracker_case_runner.py", line 203, in _initial_setup_all_classes
    i.initial_setup() # delayed set up
  File "/home/zmaw/u301513/Documents/scr/postdoc/eDNA/oceantracker/oceantracker/release_groups/polygon_release.py", line 35, in initial_setup
    crumbs=f'Polygon release {self.IDstr()}')
AttributeError: 'PolygonRelease' object has no attribute 'IDstr'

'release'
Traceback (most recent call last):
  File "/home/zmaw/u301513/Documents/scr/postdoc/eDNA/oceantracker/oceantracker/_oceantracker_main_runner.py", line 140, in _run_single
    case_summary = ot_case_runner.run_case(run_builder)
  File "/home/zmaw/u301513/Documents/scr/postdoc/eDNA/oceantracker/oceantracker/_oceantracker_case_runner.py", line 145, in run_case
    si.output_files['release_groups'] = output_util.write_release_group_netcdf()      # write release groups
  File "/home/zmaw/u301513/Documents/scr/postdoc/eDNA/oceantracker/oceantracker/util/output_util.py", line 39, in write_release_group_netcdf
    sc = rg.schedulers['release'].info
KeyError: 'release'
```

**Comment by oceantracker** [comment]
fixed
